import type { NextPage } from "next";
import Head from "next/head";
const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>Welcome to asdasd</h1>
				<p>
					Lorem, ipsum dolor sit amet consectetur adipisicing elit. Rerum in
					atque maxime tenetur illum deserunt eius est quod temporibus
					repellendus dignissimos, iste odit facilis modi incidunt. Veritatis
					cum cumque quis!
				</p>
			</main>
		</>
	);
};

export default Home;
